name: Push Test
on:
  workflow_dispatch:
  pull_request:

jobs:
  ubuntu:
    runs-on: macos-latest
    steps: 

      - name: Set up Python 3.11.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.7

      - name: Cache kahypar Build
        id: cache-kahypar
        uses: actions/cache@v3
        with:
          path: ~/kahypar.cpython-311-darwin.so
          key: kahypar_cache

      - name: Install boost
        run: brew install boost

      - name: Setup cmake
        if: ${{ steps.cache-kahypar.outputs.cache-hit != 'true' }}
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: 3.31.6

      - name: Checkout kahypar
        if: ${{ steps.cache-kahypar.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v2
        with: 
          repository: kahypar/kahypar
          submodules: recursive
          fetch-depth: 0

      - name: find site packages
        run: python -m site

      - name: Build kahypar
        if: ${{ steps.cache-kahypar.outputs.cache-hit != 'true' }}
        run: |
          git reset --hard 3802b797
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_PYTHON_INTERFACE=1 -DBUILD_TESTING=OFF
          make
          cd python
          make
          ls
          cp kahypar.cpython-311-darwin.so ~/

      - name: Install kahypar
        run: |
          python -m site
          cp ~/kahypar.cpython-311-darwin.so /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
      - name: Checkout pytket-dqc
        uses: actions/checkout@v2

      - name: Install pytket-dqc
        run: | 
          sudo apt-get install graphviz graphviz-dev
          pip install .

      - name: Install testing requirements
        run: pip install -r tests/test_requirements.txt

      - name: Tests
        run: pytest --cov-report term-missing:skip-covered --cov=src/pytket_dqc tests/ --durations=10

      - name: Type check
        run: mypy src/pytket_dqc tests
        
      - name: Code format check
        run: flake8 src/pytket_dqc tests

      - name: Examples check
        run: pytest --nbmake examples/*.ipynb

      - name: Build documentation
        run: |
          pip install -r docs/docs_requirements.txt
          cd docs
          make html

      - name: Save documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs_html
          path: docs/build/html
