name: Push Test
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install kahypar
        run: |
          git clone --depth=1 --recursive git@github.com:SebastianSchlag/kahypar.git
          cd kahypar
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=RELEASE
          make
          cd ../python
          make
          python -m site
      - name: Install pytket-dqc
        run: | 
          sudo apt-get install graphviz graphviz-dev
          pip install .
      - name: Install testing requirements
        run: pip install -r tests/test_requirements.txt
      - name: Tests
        run: pytest tests/
      - name: Type check
        run: mypy src/pytket_dqc tests
      - name: Code format check
        run: flake8 src/pytket_dqc tests