name: Push Test
on:
  workflow_dispatch:
  pull_request:

jobs:
  macos-tests:
    runs-on: macos-latest
    steps: 

      - name: Set up Python 3.11.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.7

      - name: Cache kahypar Build
        id: cache-kahypar
        uses: actions/cache@v4
        with:
          path: ~/kahypar.cpython-311-darwin.so
          key: kahypar_cache

      - name: Install boost
        run: brew install boost

      - name: Setup cmake
        if: ${{ steps.cache-kahypar.outputs.cache-hit != 'true' }}
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: 3.31.6

      - name: Checkout kahypar
        if: ${{ steps.cache-kahypar.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v4
        with: 
          repository: kahypar/kahypar
          submodules: recursive
          fetch-depth: 0

      - name: Build kahypar
        if: ${{ steps.cache-kahypar.outputs.cache-hit != 'true' }}
        run: |
          git reset --hard efa12a90
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_PYTHON_INTERFACE=1 -DBUILD_TESTING=OFF
          make
          cd python
          make
          cp kahypar.cpython-311-darwin.so ~/

      - name: Install kahypar
        run: cp ~/kahypar.cpython-311-darwin.so /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
      
      - name: Checkout pytket-dqc
        uses: actions/checkout@v4

      - name: install graphviz
        run: | 
          brew install graphviz
          export GRAPHVIZ_DIR="$(brew --prefix graphviz)"
          pip install pygraphviz \
              --config-settings=--global-option=build_ext \
              --config-settings=--global-option="-I$GRAPHVIZ_DIR/include" \
              --config-settings=--global-option="-L$GRAPHVIZ_DIR/lib"

      - name: Tests
        run: |
          pip install ".[tests]"
          pytest --cov-report term-missing:skip-covered --cov=src/pytket_dqc tests/ --durations=10

      - name: Examples check
        run: pytest --nbmake examples/*.ipynb

      - name: Build documentation
        run: |
          pip install ".[docs]"
          cd docs
          make html

      - name: Save documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs_html
          path: docs/build/html
