name: Push Test
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout kahypar
        uses: actions/checkout@v2
        with: 
          repository: kahypar/kahypar
          submodules: recursive
          fetch-depth: 1
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.16.x'
      - name: Install boost
        uses: MarkusJx/install-boost@v2.1.0
        with:
          boost_version: 1.73.0
      - name: Install kahypar
        run: |
          ls
          mkdir build && cd build
          ls
          cmake .. -DCMAKE_BUILD_TYPE=RELEASE
          make
          cd ../python
          make
          python -m site
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pytket-dqc
        run: | 
          sudo apt-get install graphviz graphviz-dev
          pip install .
      - name: Install testing requirements
        run: pip install -r tests/test_requirements.txt
      - name: Tests
        run: pytest tests/
      - name: Type check
        run: mypy src/pytket_dqc tests
      - name: Code format check
        run: flake8 src/pytket_dqc tests