name: Push Test
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps: 
      # - name: Install boost
      #   run: sudo apt-get install libboost-all-dev
      # - name: Setup cmake
      #   uses: jwlawson/actions-setup-cmake@v1.12
      #   with:
      #     cmake-version: 3.16.x
      # - name: Checkout kahypar
      #   uses: actions/checkout@v2
      #   with: 
      #     repository: kahypar/kahypar
      #     submodules: recursive
      #     fetch-depth: 1
      # - name: Install kahypar
      #   run: |
      #     mkdir build && cd build
      #     cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_TESTING=OFF -DKAHYPAR_PYTHON_INTERFACE=1
      #     make
      #     cd ../python
      #     make
      #     python -m site
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pytket-dqc
        run: | 
          sudo apt-get install graphviz graphviz-dev
          pip install .
      - name: Install testing requirements
        run: pip install -r tests/test_requirements.txt
      - name: Tests
        run: pytest tests/
      - name: Type check
        run: mypy src/pytket_dqc tests
      - name: Code format check
        run: flake8 src/pytket_dqc tests